Repository AY2021S1-CS2113T-T12-3/tp, pull requests merged in 2020-10, with the labels that each got.

#40 Add a basic skeleton
  src/main/java/seedu/duke/notebooks/Notebook.java
  src/main/java/seedu/duke/notebooks/NotebookShelf.java
  src/main/java/seedu/duke/notebooks/Page.java
  src/main/java/seedu/duke/notebooks/Section.java
  src/main/java/seedu/duke/tasks/Task.java
  src/main/java/seedu/duke/tasks/TaskList.java
  src/main/java/seedu/duke/userinterface/CliMessages.java
  src/main/java/seedu/duke/userinterface/CliUserInterface.java
  src/main/java/seedu/duke/userinterface/InputParser.java
  src/main/java/seedu/duke/userinterface/Mode.java
  src/main/java/seedu/duke/userinterface/command/Add.java
  src/main/java/seedu/duke/userinterface/command/CliCommand.java
  src/main/java/seedu/duke/userinterface/command/Done.java
  src/main/java/seedu/duke/userinterface/command/Exit.java
  src/main/java/seedu/duke/userinterface/command/Help.java
  src/main/java/seedu/duke/userinterface/command/List.java
  src/main/java/seedu/duke/userinterface/command/ModeSwitch.java
  src/main/java/seedu/duke/userinterface/command/Remove.java
  src/main/java/seedu/duke/userinterface/command/Select.java
Labels: priority.High, type.Task

#44 Created the Help command class (mostly)
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/userinterface/CliMessages.java
  src/main/java/seedu/duke/userinterface/CliUserInterface.java
  src/main/java/seedu/duke/userinterface/InputParser.java
  src/main/java/seedu/duke/userinterface/command/Add.java
  src/main/java/seedu/duke/userinterface/command/CliCommand.java
  src/main/java/seedu/duke/userinterface/command/Exit.java
  src/main/java/seedu/duke/userinterface/command/Help.java
  src/main/java/seedu/duke/userinterface/command/List.java
Labels: priority.High, type.Story

#50 Implement function to mark tasks as done
  src/main/java/seedu/duke/exceptions/InvalidUserInputException.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/tasks/Task.java
  src/main/java/seedu/duke/tasks/TaskList.java
  src/main/java/seedu/duke/userinterface/AppState.java
  src/main/java/seedu/duke/userinterface/CliMessages.java
  src/main/java/seedu/duke/userinterface/CliUserInterface.java
  src/main/java/seedu/duke/userinterface/InputParser.java
  src/main/java/seedu/duke/userinterface/command/Add.java
  src/main/java/seedu/duke/userinterface/command/CliCommand.java
  src/main/java/seedu/duke/userinterface/command/Done.java
  src/main/java/seedu/duke/userinterface/command/notebook/ListCommandNotebookMode.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Task

#78 Neilbaner dg
  docs/DeveloperGuide.md
  docs/diagrams/class/jpeg/notebook_commands.jpg
  docs/diagrams/class/jpeg/notebooks.jpg
  docs/diagrams/class/jpeg/timetable_commands.jpg
  docs/diagrams/class/visio/notebook_commands.vsdx
  docs/diagrams/class/visio/notebooks.vsdx
  docs/diagrams/class/visio/timetable_commands.vsdx
  src/main/java/seedu/duke/userinterface/InputParser.java
  src/main/java/seedu/duke/userinterface/command/Add.java
  src/main/java/seedu/duke/userinterface/command/Done.java
  src/main/java/seedu/duke/userinterface/command/timetable/DoneCommandTimetableMode.java
Labels: priority.High, type.Task

#83 Implemented JUnit test for DoneCommand
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/userinterface/CliMessages.java
  src/test/java/seedu/duke/userinterface/command/MarkAsDoneTest.java
Labels: priority.Medium, type.Task

#95 Fix the DG according to feedback from the peer review
  docs/DeveloperGuide.md
Labels: priority.High

#96 Implement saving and loading
  .gitignore
  src/main/java/seedu/duke/exceptions/CorruptFileException.java
  src/main/java/seedu/duke/exceptions/FileSavingException.java
  src/main/java/seedu/duke/notebooks/Notebook.java
  src/main/java/seedu/duke/notebooks/NotebookShelf.java
  src/main/java/seedu/duke/notebooks/Page.java
  src/main/java/seedu/duke/notebooks/Section.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/tasks/Task.java
  src/main/java/seedu/duke/tasks/TaskList.java
  src/main/java/seedu/duke/userinterface/CliUserInterface.java
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED-WIN.TXT
Labels: priority.Medium, type.Enhancement

#107 Added saveState to add, remove and done command
  src/main/java/seedu/duke/userinterface/CliUserInterface.java
  src/main/java/seedu/duke/userinterface/command/CliCommand.java
  src/main/java/seedu/duke/userinterface/command/notebook/AddCommandNotebookMode.java
  src/main/java/seedu/duke/userinterface/command/notebook/RemoveCommandNotebookMode.java
  src/main/java/seedu/duke/userinterface/command/notebook/TagCommandNotebookMode.java
  src/main/java/seedu/duke/userinterface/command/timetable/AddCommandTimetableMode.java
  src/main/java/seedu/duke/userinterface/command/timetable/DoneCommandTimetableMode.java
  src/main/java/seedu/duke/userinterface/command/timetable/RemoveCommandTimetableMode.java
  src/main/java/seedu/duke/userinterface/command/timetable/TagCommandTimetableMode.java
Labels: priority.Medium, type.Enhancement

#108 Updated Done Command to catch IndexOutOfBounds Exception
  src/main/java/seedu/duke/userinterface/command/timetable/DoneCommandTimetableMode.java
Labels: priority.Medium, type.Enhancement

#109 Edit UserGuide
  docs/UserGuide.md
  docs/diagrams/class/jpeg/duplicates_francene.jpg
  docs/diagrams/class/visio/duplicates_francene.vsdx
Labels: priority.High, type.Task

#122 Make the UG more user-focused - My attempt
  docs/UserGuide.md
Labels: priority.High, type.Task

#126 Update the Developer Guide for the Storage section
  docs/DeveloperGuide.md
  docs/diagrams/class/jpeg/storage_neil.jpg
  docs/diagrams/class/visio/storage_neil.vsdx
Labels: priority.High, type.Task

#129 Update DG Appendix F
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/storage/Storage.java
Labels: priority.High, type.Story

#133 DG - add, select features
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/class/jpeg/add_notebook.jpg
  docs/diagrams/class/jpeg/add_task.jpg
  docs/diagrams/class/jpeg/duplicates_francene.jpg
  docs/diagrams/class/jpeg/select_notebook.jpg
  docs/diagrams/class/visio/add-select_notebook.vsdx
  docs/diagrams/class/visio/duplicates_francene.vsdx
  src/main/java/seedu/duke/userinterface/command/notebook/SelectCommandNotebookMode.java
Labels: priority.High, type.Task

#128 Added line separator to UI
  src/main/java/seedu/duke/userinterface/CliMessages.java
  src/main/java/seedu/duke/userinterface/CliUserInterface.java
Labels: priority.Low, type.Enhancement

#106 Implement Personal Messages with Execution
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/userinterface/CliMessages.java
  src/main/java/seedu/duke/userinterface/CliUserInterface.java
  src/main/java/seedu/duke/userinterface/PersonalMesssageGenerator.java
  src/main/java/seedu/duke/userinterface/command/CliCommand.java
  src/main/java/seedu/duke/userinterface/command/notebook/AddCommandNotebookMode.java
  src/main/java/seedu/duke/userinterface/command/notebook/FindCommandNotebookMode.java
  src/main/java/seedu/duke/userinterface/command/notebook/ListCommandNotebookMode.java
  src/main/java/seedu/duke/userinterface/command/notebook/RemoveCommandNotebookMode.java
  src/main/java/seedu/duke/userinterface/command/notebook/TagCommandNotebookMode.java
  src/main/java/seedu/duke/userinterface/command/timetable/AddCommandTimetableMode.java
  src/main/java/seedu/duke/userinterface/command/timetable/FindCommandTimetableMode.java
  src/main/java/seedu/duke/userinterface/command/timetable/ListCommandTimetableMode.java
  src/main/java/seedu/duke/userinterface/command/timetable/RemoveCommandTimetableMode.java
  src/main/resources/txt/personalMessages.txt
Labels: priority.Medium, type.Enhancement

#144 Fix bugs for remove notebook
  notebooks.txt
  src/main/java/seedu/duke/exceptions/InvalidNotebookException.java
  src/main/java/seedu/duke/exceptions/InvalidPageException.java
  src/main/java/seedu/duke/exceptions/InvalidSectionException.java
  src/main/java/seedu/duke/notebooks/Section.java
  src/main/java/seedu/duke/userinterface/InputParser.java
  src/main/java/seedu/duke/userinterface/command/notebook/RemoveCommandNotebookMode.java
  src/main/resources/txt/nameOfUser.txt
  tasks.txt
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#147 Change find tag to be case-sensitive
  src/main/java/seedu/duke/notebooks/Notebook.java
  src/main/java/seedu/duke/userinterface/command/notebook/FindCommandNotebookMode.java
  src/main/java/seedu/duke/userinterface/command/timetable/FindCommandTimetableMode.java
Labels: type.Enhancement
